version: '3'

services:
  comex-test:
    image: mysql:5.7
    container_name: comex-test
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comex-test
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
      