CREATE TABLE ncms (
    id VARCHAR(36) PRIMARY KEY,
    code VARCHAR(55) NOT NULL,
    description TEXT NOT NULL,
    start_date VARCHAR(25) NOT NULL,
    end_date VARCHAR(25) NOT NULL,
    act_type VARCHAR(50) NOT NULL,
    act_number VARCHAR(6) NOT NULL,
    act_year VARCHAR(6) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);
